
import { useState, useEffect } from 'react';
import { Code, Sparkles, Zap } from 'lucide-react';

const Hero = () => {
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    setIsVisible(true);
  }, []);

  return (
    <section className="relative pt-32 pb-20 overflow-hidden">
      {/* Purple glow background effect */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full max-w-4xl h-64 bg-purple-glow opacity-70 blur-3xl"></div>
      
      <div className="section-container relative z-10">
        <div className="text-center max-w-4xl mx-auto">
          <div className={`transform transition-all duration-700 ${isVisible ? 'opacity-100' : 'opacity-0 translate-y-10'}`}>
            <div className="inline-flex items-center space-x-1 bg-white/90 backdrop-blur-sm px-4 py-1.5 rounded-full shadow-sm mb-6 border border-codegenius-purple/20">
              <Sparkles size={16} className="text-codegenius-purple" />
              <span className="text-sm font-medium text-codegenius-black">Revolutionizing Code Generation</span>
            </div>
          </div>
          
          <h1 
            className={`text-5xl md:text-6xl lg:text-7xl font-bold leading-tight mb-6 transform transition-all duration-700 delay-150 ${
              isVisible ? 'opacity-100' : 'opacity-0 translate-y-10'
            }`}
          >
            <span className="text-gradient">AI Code Generator</span>
            <br />
            <span className="text-codegenius-black">Simplified & Powerful</span>
          </h1>
          
          <p 
            className={`text-lg md:text-xl text-codegenius-black/80 max-w-3xl mx-auto mb-10 transform transition-all duration-700 delay-300 ${
              isVisible ? 'opacity-100' : 'opacity-0 translate-y-10'
            }`}
          >
            Transform your ideas into production-ready code in seconds. CodeGenius uses advanced AI to generate clean, efficient, and maintainable code across multiple languages and frameworks.
          </p>
          
          <div 
            className={`flex flex-col sm:flex-row gap-4 justify-center transform transition-all duration-700 delay-500 ${
              isVisible ? 'opacity-100' : 'opacity-0 translate-y-10'
            }`}
          >
            <a href="https://code-gnerator-one.vercel.app/" className="btn-primary">
              <Zap size={18} className="mr-2" />
              Try CodeGenius Free
            </a>
            <a href="#features" className="btn-secondary">
              <Code size={18} className="mr-2" />
              Explore Features
            </a>
          </div>
        </div>
        
        {/* Code preview mockup */}
        <div 
          className={`mt-16 relative max-w-4xl mx-auto transform transition-all duration-1000 delay-700 ${
            isVisible ? 'opacity-100' : 'opacity-0 translate-y-20'
          }`}
        >
          <div className="glass-card overflow-hidden">
            <div className="bg-codegenius-black/90 p-3 flex items-center space-x-2">
              <div className="flex space-x-1.5">
                <div className="h-3 w-3 rounded-full bg-red-500"></div>
                <div className="h-3 w-3 rounded-full bg-yellow-500"></div>
                <div className="h-3 w-3 rounded-full bg-green-500"></div>
              </div>
              <div className="text-white/80 text-sm font-mono">codegenius-demo.js</div>
            </div>
            <div className="bg-codegenius-black/95 p-6 font-mono text-sm text-white/90 overflow-x-auto">
              <pre><code>
{`// Generated by CodeGenius
import React, { useState, useEffect } from 'react';

const CodeGeniusDemo = () => {
  const [loading, setLoading] = useState(true);
  const [data, setData] = useState(null);

  useEffect(() => {
    // Fetch data from API
    async function fetchData() {
      try {
        const response = await fetch('/api/data');
        const result = await response.json();
        setData(result);
        setLoading(false);
      } catch (error) {
        console.error('Error:', error);
        setLoading(false);
      }
    }

    fetchData();
  }, []);

  return (
    <div className="container">
      {loading ? (
        <div className="loading-spinner" />
      ) : (
        <div className="data-display">
          {/* Render your data here */}
          {JSON.stringify(data)}
        </div>
      )}
    </div>
  );
};

export default CodeGeniusDemo;`}
              </code></pre>
            </div>
          </div>
          
          {/* Floating elements for visual interest */}
          <div className="absolute -right-10 -top-10 h-20 w-20 bg-codegenius-purple/10 rounded-full backdrop-blur-xl animate-float"></div>
          <div className="absolute -left-5 bottom-10 h-12 w-12 bg-codegenius-purple/10 rounded-full backdrop-blur-xl animate-float animation-delay-3"></div>
        </div>
      </div>
    </section>
  );
};

export default Hero;
